version: '3'
services:
  dashboard:
    image: 866002118117.dkr.ecr.eu-north-1.amazonaws.com/pod16-dockerproject:latest
    container_name: dashboard-container
    ports:
      - "3000:3000"
    restart: always


